### ISSUE TITLE
Grid with multiple cells

### ISSUE THREAD

**Issue by Mirrorigin** [uiowahjmjohnsonselt2024/projectdirectory-selt_2024_team_005#9]
As a player, I want a grid with multiple cells that each has different states, so I can interact with them and make decisions.

**Comment by rmdna-uiowa** [comment]
We'll be breaking this user story down into three parts into the future, something along the lines of:
As a player, I want to have a 6x6 grid that I can interact with
As a player, I want to be able to move from each cell in the grid to another cell
As a player, I want to be able to interact with each individual cell in that 6x6 grid
